platform :ios, '7.0'
pod 'XGPush'
pod 'AFNetworking'
pod 'MJRefresh', :git => 'https://github.com/hong4cong/MJRefresh.git',:commit => 'de9df94'
#pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'HMSegmentedControl'
pod 'Reachability'
pod 'MJExtension'
pod 'KxMenu'
pod 'UMengAnalytics-NO-IDFA'
#pod 'REFrostedViewController'
#pod 'AlipaySDK', :git => 'https://github.com/hong4cong/AlipaySDK.git'
inhibit_all_warnings!

